import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

interface Enquiry { name: string; email: string; phone: string; destination: string; studyLevel: string; message: string; }
interface ChatMessage { role: 'assistant' | 'user'; text: string; }

@Component({
  selector: 'has-root', standalone: true, imports: [CommonModule, FormsModule],
  template: `
  <header class="site-header"><a class="brand" href="#home"><span class="brand-mark">H</span><span>harvest<span class="brand-light"> abroad studies</span><small>YOUR GLOBAL FUTURE STARTS HERE</small></span></a>
    <button class="menu-toggle" type="button" (click)="menuOpen = !menuOpen" aria-label="Toggle navigation">☰</button>
    <nav [class.open]="menuOpen"><a href="#destinations" (click)="menuOpen=false">Destinations</a><a href="#packages" (click)="menuOpen=false">Packages</a><a href="#process" (click)="menuOpen=false">How it works</a><a href="#faq" (click)="menuOpen=false">FAQs</a><a class="nav-cta" href="#contact" (click)="menuOpen=false">Free consultation <span>↗</span></a></nav>
  </header>
  <main>
    <section class="hero" id="home"><div class="hero-copy"><div class="eyebrow"><span class="eyebrow-dot"></span> YOUR JOURNEY. YOUR DESTINATION.</div><h1>Think beyond.<br><em>Study abroad.</em></h1><p class="hero-lead">Big dreams deserve a world of opportunity. Get personalised guidance to choose your destination, course and next big step.</p><div class="hero-actions"><a class="button button-primary" href="#contact">Plan my journey <span>↗</span></a><a class="text-link" href="#destinations"><span class="play">↓</span> Explore destinations</a></div><div class="trust-line"><div class="avatar-stack"><span>H</span><span>✦</span><span>✈</span></div><span>Personal guidance, from shortlist to take-off.</span></div></div>
      <div class="hero-art"><div class="art-orbit orbit-one"></div><div class="art-orbit orbit-two"></div><div class="sun-disc"></div><div class="art-card card-top"><span class="card-icon">✦</span><span><b>Your next chapter</b><small>Starts with one conversation</small></span></div><div class="globe"><div class="globe-lat"></div><div class="globe-lon"></div><div class="globe-land land-one"></div><div class="globe-land land-two"></div><span class="globe-pin">✈</span></div><div class="art-card card-bottom"><span class="mini-flag">◎</span><span><b>Global possibilities</b><small>Find the right fit for you</small></span></div><div class="floating-star star-a">✳</div><div class="floating-star star-b">✦</div><div class="art-caption">GO FURTHER. GROW FURTHER.</div></div>
      <div class="hero-bottom"><span>01 / FIND YOUR DIRECTION</span><span>GUIDANCE THAT MOVES WITH YOU <b>↘</b></span></div></section>

    <section class="intro section-pad"><div class="section-kicker">A WORLD OF CHOICE</div><div class="intro-grid"><h2>Your future is<br>not one-size-fits-all.</h2><div><p>Choosing where to study is a big decision. We help you make it with clarity — matching your goals, interests and budget with study opportunities around the world.</p><a class="under-link" href="#process">Discover our approach <span>↗</span></a></div></div><div class="stats-row"><div><strong>01</strong><span>Personalised planning</span></div><div><strong>02</strong><span>Destination guidance</span></div><div><strong>03</strong><span>Application support</span></div><div><strong>04</strong><span>One step at a time</span></div></div></section>

    <section class="destinations section-pad" id="destinations"><div class="section-head"><div><div class="section-kicker">WHERE WILL YOU GO?</div><h2>Choose your <em>world.</em></h2></div><p>Explore popular study destinations and discover which path feels right for you.</p></div><div class="destination-grid">
      <article class="destination-card europe"><div class="destination-number">01 / EUROPE</div><div class="destination-symbol">✧</div><div class="destination-content"><h3>Europe</h3><p>Explore diverse cultures, international classrooms and varied study pathways.</p><button (click)="chooseDestination('Europe')">Explore Europe <span>↗</span></button></div></article>
      <article class="destination-card usa"><div class="destination-number">02 / UNITED STATES</div><div class="destination-symbol">✳</div><div class="destination-content"><h3>United States</h3><p>Discover a wide range of universities, programmes and campus experiences.</p><button (click)="chooseDestination('USA')">Explore the USA <span>↗</span></button></div></article>
      <article class="destination-card uk"><div class="destination-number">03 / UNITED KINGDOM</div><div class="destination-symbol">⌁</div><div class="destination-content"><h3>United Kingdom</h3><p>Find courses and institutions that fit your academic ambitions.</p><button (click)="chooseDestination('UK')">Explore the UK <span>↗</span></button></div></article>
      <article class="destination-card canada"><div class="destination-number">04 / CANADA</div><div class="destination-symbol">✺</div><div class="destination-content"><h3>Canada</h3><p>Compare study options and plan your next chapter with confidence.</p><button (click)="chooseDestination('Canada')">Explore Canada <span>↗</span></button></div></article>
      <article class="destination-card australia"><div class="destination-number">05 / AUSTRALIA</div><div class="destination-symbol">◈</div><div class="destination-content"><h3>Australia</h3><p>Explore programmes and student experiences across Australia.</p><button (click)="chooseDestination('Australia')">Explore Australia <span>↗</span></button></div></article>
      <article class="destination-card more"><div class="destination-number">06 / YOUR NEXT POSSIBILITY</div><div class="destination-symbol">＋</div><div class="destination-content"><h3>Somewhere else?</h3><p>Germany, Ireland or another destination? Tell us what you have in mind.</p><button (click)="chooseDestination('Other')">Find my destination <span>↗</span></button></div></article>
    </div></section>

    <section class="packages section-pad" id="packages"><div class="section-head"><div><div class="section-kicker">SUPPORT THAT FITS YOUR PLAN</div><h2>Your journey.<br><em>Your way.</em></h2></div><p>Start with a package that reflects the kind of guidance you need. Final services and fees should be confirmed with our counsellor.</p></div><div class="package-grid">
      <article class="package-card"><div class="package-label">01 / START HERE</div><h3>Explore</h3><p class="package-summary">For students at the beginning of their search.</p><div class="package-price">Custom quote <small>based on your needs</small></div><ul><li>Initial profile discussion</li><li>Destination and course exploration</li><li>Next-step guidance</li></ul><button class="button button-outline" (click)="choosePackage('Explore')">Ask about Explore <span>↗</span></button></article>
      <article class="package-card package-featured"><div class="popular-pill">STUDENT FAVOURITE</div><div class="package-label">02 / BUILD YOUR PLAN</div><h3>Plan</h3><p class="package-summary">For students ready to shortlist courses and institutions.</p><div class="package-price">Custom quote <small>based on your needs</small></div><ul><li>Profile and shortlist discussion</li><li>Application planning support</li><li>Document checklist guidance</li></ul><button class="button button-primary" (click)="choosePackage('Plan')">Ask about Plan <span>↗</span></button></article>
      <article class="package-card"><div class="package-label">03 / FULLER GUIDANCE</div><h3>Prepare</h3><p class="package-summary">For students who want structured support through key steps.</p><div class="package-price">Custom quote <small>based on your needs</small></div><ul><li>Application process guidance</li><li>Interview and preparation tips</li><li>Pre-departure checklist</li></ul><button class="button button-outline" (click)="choosePackage('Prepare')">Ask about Prepare <span>↗</span></button></article>
    </div><p class="fine-print">Package names and inclusions are starter examples. Confirm actual fees, services, eligibility and timelines directly with Harvest Abroad Studies. Admission and visa outcomes are never guaranteed.</p></section>

    <section class="process section-pad" id="process"><div class="process-left"><div class="section-kicker">A CLEARER WAY FORWARD</div><h2>From “what if?”<br>to <em>what’s next.</em></h2><p>You don't have to figure out every detail at once. Take the process one step at a time, with a plan built around you.</p><a class="button button-light" href="#contact">Start with a conversation <span>↗</span></a><div class="process-decoration">H<span>✦</span></div></div><div class="process-steps"><article><span>01</span><div><h3>Tell us about your goals</h3><p>Share your preferred course, budget, academic background and ambitions.</p></div><b>↗</b></article><article><span>02</span><div><h3>Explore your options</h3><p>Discuss destinations and study pathways that may fit your profile.</p></div><b>↗</b></article><article><span>03</span><div><h3>Build your action plan</h3><p>Understand the documents, applications and next steps involved.</p></div><b>↗</b></article><article><span>04</span><div><h3>Prepare for what’s ahead</h3><p>Get organised for the next stages of your study-abroad journey.</p></div><b>↗</b></article></div></section>

    <section class="faq section-pad" id="faq"><div><div class="section-kicker">GOOD QUESTIONS, HONEST ANSWERS</div><h2>Before you <em>take off.</em></h2><p>Not sure where to start? Here are a few helpful first answers.</p><a class="under-link" href="#contact">Ask us something else <span>↗</span></a></div><div class="faq-list"><article *ngFor="let item of faqs; let i = index" class="faq-item" [class.expanded]="openFaq === i"><button (click)="openFaq = openFaq === i ? -1 : i"><span>{{item.q}}</span><b>{{openFaq === i ? '−' : '+'}}</b></button><p *ngIf="openFaq === i">{{item.a}}</p></article></div></section>

    <section class="contact section-pad" id="contact"><div class="contact-copy"><div class="section-kicker">LET'S MAKE A PLAN</div><h2>Your next chapter<br>starts <em>right here.</em></h2><p>Tell us a little about yourself. Our team can follow up to discuss your study-abroad goals and possible next steps.</p><div class="contact-detail"><span>✉</span><div><small>EMAIL</small><a href="mailto:hello@harvestabroadstudies.com">hello&#64;harvestabroadstudies.com</a></div></div><div class="contact-detail"><span>☎</span><div><small>PHONE / WHATSAPP</small><p>Update with your official contact number</p></div></div><p class="fine-print">Contact details shown here are placeholders. Replace them with verified business details before publishing.</p></div>
      <form class="enquiry-form" (ngSubmit)="submitEnquiry()" #enquiryForm="ngForm"><div class="form-heading"><h3>Let's get to know you.</h3><p>All fields marked * are required.</p></div><div class="form-row"><label>Full name *<input name="name" [(ngModel)]="enquiry.name" required minlength="2" placeholder="Your full name"></label><label>Email address *<input name="email" [(ngModel)]="enquiry.email" required email type="email" placeholder="you@example.com"></label></div><div class="form-row"><label>Phone / WhatsApp *<input name="phone" [(ngModel)]="enquiry.phone" required minlength="7" placeholder="Your contact number"></label><label>Preferred destination *<select name="destination" [(ngModel)]="enquiry.destination" required><option value="">Choose destination</option><option>Europe</option><option>USA</option><option>UK</option><option>Canada</option><option>Australia</option><option>Germany</option><option>Ireland</option><option value="Other">Other / not sure</option></select></label></div><label>Study level<select name="studyLevel" [(ngModel)]="enquiry.studyLevel"><option value="">Select study level</option><option>Undergraduate</option><option>Postgraduate / Master's</option><option>Diploma</option><option>Doctoral / PhD</option><option>Not sure yet</option></select></label><label>What would you like help with?<textarea name="message" [(ngModel)]="enquiry.message" rows="3" placeholder="Tell us about your course, timeline or questions..."></textarea></label><button class="button button-primary submit-button" type="submit" [disabled]="submitting || !enquiryForm.valid">{{submitting ? 'Sending…' : 'Send my enquiry'}} <span>↗</span></button><p class="form-status" *ngIf="formMessage" [class.error]="formError" role="status">{{formMessage}}</p><small class="privacy-note">Your information will be used to respond to your enquiry. Avoid entering passport numbers or other sensitive identity details.</small></form></section>
  </main>
  <footer><a class="brand footer-brand" href="#home"><span class="brand-mark">H</span><span>harvest<span class="brand-light"> abroad studies</span><small>YOUR GLOBAL FUTURE STARTS HERE</small></span></a><p>Make the world part of your classroom.</p><span>© {{year}} Harvest Abroad Studies</span></footer>

  <button class="chat-launcher" (click)="chatOpen = !chatOpen" [attr.aria-expanded]="chatOpen" aria-label="Open study assistant">{{chatOpen ? '×' : '✦'}}<span *ngIf="!chatOpen">Ask our study assistant</span></button>
  <aside class="chat-panel" *ngIf="chatOpen"><div class="chat-header"><div class="chat-avatar">✦</div><div><b>Harvest Study Assistant</b><small>Ask about destinations and next steps</small></div><button (click)="chatOpen=false" aria-label="Close chat">×</button></div><div class="chat-messages"><div class="chat-message assistant">Hi! 👋 I'm here to help you get started. What would you like to know about studying abroad?</div><div *ngFor="let msg of chatMessages" class="chat-message" [class.user]="msg.role === 'user'">{{msg.text}}</div><div *ngIf="chatBusy" class="chat-message assistant">Thinking…</div></div><form class="chat-input" (ngSubmit)="sendChat()"><input name="chatInput" [(ngModel)]="chatInput" placeholder="Ask your question…" aria-label="Chat question" required><button [disabled]="chatBusy || !chatInput.trim()" aria-label="Send message">➤</button></form><small class="chat-disclaimer">General guidance only; confirm official requirements with the relevant institution and authorities.</small></aside>
  `
})
export class AppComponent {
  year = new Date().getFullYear(); menuOpen = false; openFaq = 0; chatOpen = false; chatBusy = false; submitting = false; formMessage = ''; formError = false; chatInput = '';
  chatMessages: ChatMessage[] = [];
  enquiry: Enquiry = { name: '', email: '', phone: '', destination: '', studyLevel: '', message: '' };
  faqs = [
    { q: 'When should I start planning to study abroad?', a: 'It is useful to start early because course deadlines, document preparation and visa processes vary by destination and institution. Share your intended intake with a counsellor so you can make a realistic timeline.' },
    { q: 'Can you help me choose a country and course?', a: 'Yes. Start by considering your academic background, subject interests, budget, language requirements and long-term goals. A counsellor can help you compare options; final eligibility is determined by each institution.' },
    { q: 'What documents might I need?', a: 'Requirements vary, but may include academic transcripts, passport, English-language test results, a statement of purpose, recommendation letters and financial documents. Check the official institution and visa guidance for your specific case.' },
    { q: 'Do you guarantee admission or a visa?', a: 'No responsible adviser can guarantee admission or a visa. Decisions are made by the relevant university and immigration authority. We can help you understand the process and prepare your application.' },
    { q: 'How much do the packages cost?', a: 'Fees depend on the support required and the destination. The package cards are illustrative only; contact Harvest Abroad Studies for verified services, inclusions and pricing before making a decision.' }
  ];
  constructor(private http: HttpClient) {}
  chooseDestination(destination: string) { this.enquiry.destination = destination === 'Other' ? 'Other' : destination; document.getElementById('contact')?.scrollIntoView({ behavior: 'smooth' }); }
  choosePackage(packageName: string) { this.enquiry.message = `I would like to know more about the ${packageName} package.`; document.getElementById('contact')?.scrollIntoView({ behavior: 'smooth' }); }
  submitEnquiry() {
    this.submitting = true; this.formMessage = ''; this.formError = false;
    this.http.post<{message:string}>('/api/enquiries', this.enquiry).subscribe({
      next: res => { this.formMessage = res.message || 'Thanks! Your enquiry has been received.'; this.enquiry = { name:'', email:'', phone:'', destination:'', studyLevel:'', message:'' }; this.submitting = false; },
      error: () => { this.formError = true; this.formMessage = 'We could not submit your enquiry right now. Please try again later or contact the team directly.'; this.submitting = false; }
    });
  }
  sendChat() {
    const question = this.chatInput.trim(); if (!question || this.chatBusy) return;
    this.chatMessages.push({ role: 'user', text: question }); this.chatInput = ''; this.chatBusy = true;
    this.http.post<{reply:string}>('/api/chat', { message: question }).subscribe({
      next: res => { this.chatMessages.push({ role: 'assistant', text: res.reply || this.localAnswer(question) }); this.chatBusy = false; },
      error: () => { this.chatMessages.push({ role: 'assistant', text: this.localAnswer(question) }); this.chatBusy = false; }
    });
  }
  private localAnswer(question: string): string {
    const q = question.toLowerCase();
    if (q.includes('cost') || q.includes('fee') || q.includes('budget')) return 'Costs vary by country, course, university and living expenses. Tell us your preferred destination and budget in the enquiry form so a counsellor can discuss options. Package prices must be confirmed directly.';
    if (q.includes('visa')) return 'Visa requirements depend on the destination and your circumstances. Check the official immigration website for current requirements; our team can help you understand the preparation steps, but no visa outcome can be guaranteed.';
    if (q.includes('document')) return 'Common documents can include academic transcripts, passport, language-test results, statement of purpose and financial evidence. The exact list depends on the institution, course and visa category.';
    if (q.includes('europe') || q.includes('usa') || q.includes('canada') || q.includes('uk') || q.includes('australia') || q.includes('germany') || q.includes('ireland')) return 'The best destination depends on your course, budget, academic profile and goals. Use the destination cards on this page, then send an enquiry so the team can discuss suitable options.';
    if (q.includes('admission') || q.includes('apply') || q.includes('application')) return 'A good first step is to shortlist courses, check entry requirements and deadlines, and prepare your documents. Requirements vary by institution, so confirm details on official university websites.';
    return 'I can help with general questions about destinations, applications, documents, budgets and planning. For personalised advice, share your preferred course and destination through the enquiry form. For official requirements, consult the relevant university or government website.';
  }
}
